<?php
/**
 * 这是图片上传后上传到微信服务器获得素材mediarId
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/11/27 0027
 * Time: 下午 2:55
 */

namespace zc\wechat\behaviors;

use Yii;
use yii\base\Behavior;
use yii\db\ActiveRecord;
use EasyWeChat\Foundation\Application;
use zc\wechat\models\Wechat;
class ImageBehavior extends Behavior
{
    /**
     * @var ActiveRecord
     */
    //public $owner;
    /**
     * @var string  资源相对路径地址
     */
    public $sourcePath;//
    /**
     * @var bool 是否临时文件
     */
    public $isTem = false;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = Yii::$app->glide->sourcePath .'/';
    }

    /**
     * @return array
     */
    public function events()
    {
        return [
            //ActiveRecord::EVENT_AFTER_VALIDATE => 'afterValidateImage',
            ActiveRecord::EVENT_BEFORE_INSERT => 'beforeSaveImage',
            ActiveRecord::EVENT_BEFORE_UPDATE => 'beforeSaveImage',
        ];
    }

    /**
     * 上传图片素材到微信服务器
     */
    //public function afterValidateImage(){
    public function beforeSaveImage(){
        $options = [
            /**
             * 账号基本信息，请从微信公众平台/开放平台获取
             */
            'app_id'  => '',         // AppID
            'secret'  => '',     // AppSecret
            'token'   => '',          // Token
            'aes_key' => '',                    // EncodingAESKey，安全模式下请一定要填写！！！

            // ...
        ];
        $id = 1;
        $wechat = Wechat::find(['id'=>$id])->one();



        $options['app_id'] = $wechat->appID;
        $options['secret'] = $wechat->secret;
        $options['token'] = $wechat->token;
        $options['aes_key'] = $wechat->encoding_aes_key;


        $app = new Application($options);
        if($this->isTem){
            // 临时素材
            $material = $app->material_temporary;
        }else{
            // 永久素材
            $material = $app->material;
        }
        $realPath = Yii::getAlias($this->sourcePath . $this->owner->img_banner);
        $result = $material->uploadImage($realPath);//微信素材  上传图片



        $this->owner->MediaId = $result['media_id'];//MediaId赋值
    }

}